project:
  type: website
  resources:
    - esercizi.qmd
    - images/Dispensa_23.pdf
website:
  title: "Misure Industriali"
  navbar:
    left:
      - href: r_brief.qmd
        text: R in breve
      - href: teoria.qmd
        text: Teoria
      - href: esercizi.qmd
        text: Esercitazioni
      - about.qmd
execute:
  freeze: auto
format:
  html:
    lang: it 
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true



