project:
  type: website
  resources:
    - esercizi.qmd
website:
  title: "Misure Industriali"
  navbar:
    left:
      - href: r_brief.qmd
        text: R in breve
      - href: fft.qmd
        text: Trasformate
      - href: filtri.qmd
        text: Filtri
      - about.qmd
execute:
  freeze: auto
format:
  html:
    lang: it 
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true



